services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

  redis-cli:
    image: redis:7
    container_name: redis-cli
    entrypoint: ["redis-cli", "-h", "redis"]
    depends_on:
      - redis
    stdin_open: true
    tty: true

volumes:
  redis-data:
  pgdata: